/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Environment */

#ifndef _Included_Environment
#define _Included_Environment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Environment
 * Method:    hasMoreVariable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Environment_hasMoreVariable
  (JNIEnv *, jobject);

/*
 * Class:     Environment
 * Method:    getVariable
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Environment_getVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
